language: java
jdk:
    openjdk11
install: true
before_install:
  - npm install -g @angular/cli@7.3.9
stages:
  - name: deliver
jobs:
  include:
      - stage: deliver
        script:
          - cd frontend
          - npm install -f
          - node -v
          - npm cache clean -f
          - npm install -g n
          - sudo mkdir /usr/local/n
          - sudo chown -R $(whoami) $_
          - n latest
          - sudo ln -sf /usr/local/n/versions/node/12.6.0 /usr/bin/node
          - node -v
          - npm install @types/node --save-dev
          - npm run build
          - docker build -t studentproject/ocado-tim-frontend:latest .
          - docker login -u "studentproject" -p "$DOCKER_PASSWORD"
          - docker push studentproject/ocado-tim-frontend:latest
