language: java
jdk:
    openjdk11
install: true
before_install:
  - npm install -g @angular/cli
stages:
  - name: test
  - name: build
  - name: deliver
    if: branch = develop
  - name: deploy
    if: branch = maste
jobs:
  include:
      - stage: test
        script:
         - cd backend
         - chmod +x mvnw
         - mvn test
