language: java
jdk:
    openjdk11
install: true
before_install:
  - npm install -g @angular/cli@latest
  - nvm ls-remote
  - nvm install 12.6.0
  - nvm use 12.6.0
stages:
  - name: deliver
jobs:
  include:
      - stage: deliver
        script:
          - cd frontend
          - npm install -f
          - node -v
          - npm install @types/node --save-dev
          - npm run build
          - docker build -t studentproject/ocado-tim-frontend:latest .
          - docker login -u "studentproject" -p "$DOCKER_PASSWORD"
          - docker push studentproject/ocado-tim-frontend:latest
