language: java
jdk:
    adoptopenjdk/openjdk11
install: true
before_install:
  - npm install -g @angular/cli
stages:
  - name: test
jobs:
  include:
      - stage: test
        script:
         - cd backend
         - chmod +x mvnw
         - mvn test
