language: java
jdk:
    openjdk11
install: true
before_install:
  - npm install -g @angular/cli@7.3.9
stages:
  - name: test
  - name: build
  - name: deliver
  - name: deploy
    if: branch = master
jobs:
  include:
      - stage: test
        script:
         - cd backend
         - chmod +x mvnw
         - mvn test
      - stage: build
        script:
         - cd frontend
         - npm i -f
         - ng build
         - cd -
         - cd backend
         - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - stage: deliver
        script:
          - cd backend
          - mvn package
          - docker build -t studentproject/ocado-tim-backend:latest .
          - cd -
          - cd frontend
          - npm install -f
          - npm run build
          - docker build -t studentproject/ocado-tim-frontend:latest .
          - docker login -u "studentproject" -p "$DOCKER_PASSWORD"
          - docker push studentproject/ocado-tim-backend:latest
          - docker push studentproject/ocado-tim-frontend:latest
