security:
  jwt:
    key: classpath:public.txt
    client-id: timApp
    client-secret: OcadoProject
    token-endpoint: http://localhost:9090/oauth/token
spring:
  profiles:
    active: develop
  main:
    allow-bean-definition-overriding: true