logging:
  level:
    org:
      springframework:
        security: DEBUG
security:
  jwt:
    public-key: classpath:public.txt
    clientId: timApp
    clientSecret: OcadoProject
    tokenEndpoint: http://localhost:9090/oauth/token
spring:
  profiles:
    active: h2
