image: maven:3.6.0-jdk-11
pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn clean install
  branches:
    master:
      - step:
          caches:
            - maven
          script:
            - cd backend
            - mvn clean install
            - docker build -t studentproject/ocado-tim-backend:latest ./
            - docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PASSWORD
            - docker push studentproject/ocado-tim-backend:latest
            - cd ..
            - cd frontend
            - npm run build
            - docker build -t studentproject/ocado-tim-frontend:latest ./
            - docker push studentproject/ocado-tim-frontend:latest
          services:
            - docker
